language: node_js
matrix:
    fast_finish: true
    allow_failures:
        - node_js: "5"
node_js:
    - "0.12"
    - "0.10"
    - "4"
    - "5"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
        - NAME=appname
        - TOKEN=apptoken

before_install:
    - npm install -g npm@latest-2
before_script:
    - npm run travis-before

deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
    node: "4"
